### ISSUE TITLE
Mudança de nome

### ISSUE THREAD

**Issue by paladini** [btcbrdev/dominandobitcoin-site#2]
Acho que o nome "Dominando Bitcoin" fica muito tradução literal, não é uma tradução adequada ao português.

O que acham de "**Dominando o Bitcoin**"?

**Comment by ghost** [comment]
Concordo.

**Comment by Anderson-Juhasc** [comment]
Legal, acho q o nome do repositório pode continuar o msm, só mudar o título.

**Comment by paladini** [comment]
Okay, eu cuido disso mais tarde :)
