### ISSUE TITLE
Novo colaborador

### ISSUE THREAD

**Issue by paladini** [btcbrdev/dominandobitcoin-site#5]
Pessoal, o @fernandoyo está interessado em contribuir de alguma forma com a tradução (mesmo que seja pouco, qualquer ajuda é bem vinda) e não sabe muito bem de GitHub. 

Só queria apresentar ele aqui e dizer para que tentem ajudar ele se este tiver alguma dúvida sobre as traduções ou sobre como o GitHub funciona.

Seja bem vindo, marujo! :)

**Comment by Anderson-Juhasc** [comment]
Bem vindo @fernandoyo, sua ajuda será bem vinda! Você pode começar sua tradução na wiki: https://github.com/btcbrdev/dominandobitcoin/wiki, só necessário saber usar markdown que não é nada complexo.

**Comment by fernandoyo** [comment]
Opa!
Valeu, qualquer coisa eu peço ajuda.

2015-02-19 12:49 GMT-04:00 Anderson Juhasc notifications@github.com:

**Comment by Anderson-Juhasc** [comment]
:+1:
